### ISSUE TITLE
Could not load icon 'RiskExtensionMediumIcon.png' specified in 'icons'.

### ISSUE THREAD

**Issue by PippoCalogero** [jmirch/RiskAnalysisExtension#2]
Hello,
I followed your instruction but when I clicked on "Load unpacked", it gave me this message "Could not load icon 'RiskExtensionMediumIcon.png' specified in 'icons'."
Did I make some mistake?
Thanks

**Comment by jmirch** [comment]
Hi PippoCalogero

I need to update the ReadMe but I've actually published the extension to
the Chrome Web Store now so you no longer need to follow those
instructions.
https://chrome.google.com/webstore/detail/risk-analysis-extension/mdndhijfmbcembmjeihdpafnmfkojhmg?hl=en&authuser=2

Those instructions were initially added so that my friends could use the
extension while I was still working on it.

Thanks,
jmirch

**Comment by PippoCalogero** [comment]
Thank you, a very nice tool.

**Comment by jmirch** [comment]
Thanks! Glad you like it!
